[project]
authors = ["shughes.uk <shughes.uk@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "resume"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
frontend-build = { cmd = "npm run build", cwd = "frontend" }
frontend-deploy = { cmd = "npm run deploy", cwd = "frontend" }
frontend-dev = { cmd = "npm run dev", cwd = "frontend" }
frontend-format = { cmd = "npm run format", cwd = "frontend" }
frontend-install = { cmd = "npm install", cwd = "frontend" }
frontend-lint = { cmd = "npm run lint", cwd = "frontend" }

[dependencies]
awscli = ">=2.15.36,<2.16"
git = ">=2.44.0,<2.45"
nodejs = ">=20.9.0,<20.10"
pre-commit = ">=3.7.0,<3.8"
python = ">=3.11.0,<3.12"
terraform = ">=1.7.5,<1.8"

[pypi-dependencies]
boto3 = "*"
click = "*"
ruff = "*"
