[workspace]
authors = ["shughes.uk <shughes.uk@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "resume"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
frontend-build = { cmd = "npm run build", cwd = "frontend", depends-on = [
    "frontend-lint",
] }
frontend-deploy = { cmd = "python scripts/deploy_frontend.py", cwd = ".", depends-on = [
    "frontend-build",
] }
frontend-dev = { cmd = "npm run dev", cwd = "frontend" }
frontend-format = { cmd = "npm run format", cwd = "frontend" }
frontend-install = { cmd = "npm install", cwd = "frontend" }
frontend-lint = { cmd = "npm run lint", cwd = "frontend", depends-on = [
    "frontend-install",
] }
terraform-apply = { cmd = "terraform apply", cwd = "terraform", depends-on = [
    "terraform-init",
] }
terraform-format = { cmd = "terraform fmt", cwd = "terraform" }
terraform-init = { cmd = "terraform init -input=false", cwd = "terraform" }
terraform-plan = { cmd = "terraform plan -input=false", cwd = "terraform", depends-on = [
    "terraform-init",
] }

[dependencies]
awscli = ">=2.36.42,<3"
git = ">=2.55.0,<3"
nodejs = ">=26.8.2,<26.9"
pre-commit = ">=4.6.2,<5"
python = ">=3.14.7,<3.15"
terraform = ">=1.16.1,<2"

[pypi-dependencies]
boto3 = ">=1.43.98, <2"
click = ">=8.5.0, <9"
ruff = ">=0.16.8, <0.17"
