[project]
name = "resume"
version = "0.1.0"
description = "Add a short description here"
authors = ["shughes.uk <shughes.uk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
git = ">=2.44.0,<2.45"
nodejs = ">=20.9.0,<20.10"
pnpm = ">=8.15.6,<8.16"
