name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deployment:
    environment: production
    concurrency: production
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::905418398753:role/github-actions-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-1"
      - uses: prefix-dev/setup-pixi@v0.5.1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          cache: true
          locked: true
      - name: Deploy
        run: pixi run frontend-deploy
