name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          cache: true
      - name: Lint
        run: pixi run frontend-lint
      - name: Format
        run: pixi run frontend-format
      - name: Build-check
        run: pixi run frontend-build
