name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          run_install: |
            - cwd: frontend
      - name: Move to frontend
        run: cd frontend
      - name: Install modules
        run: pnpm install
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
