name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          cache: true
      - name: Pnpm cache
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install
        run: pixi run frontend-install
      - name: Lint
        run: pixi run frontend-lint
      - name: Format
        run: pixi run frontend-format
      - name: Build-check
        run: pixi run frontend-build
