name: CI
on: push
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          cache: true
          locked: true
      - name: install frontend
        run: pixi run frontend-install
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: pre-commit/action@v3.0.1
